api_endpoint: "http://10.254.138.189:8119"
model: "Meta-Llama-3.1-8B-Instruct"
output_dir: "/raid/vinh/resources/results"
splits:
  - gsm8k
  - math
  - olympiadbench
  - omnimath
verifier_type: parc
verifier_kwargs: {}
construction_kwargs: {}
generation_kwargs:
  temperature: 0.0
  top_p: 0.8
  top_k: 1
  max_tokens: 4096
dataset_path: "/raid/vinh/resources/datasets/ProcessBench"
sample_size: 250
use_voting: false
voting_n: 8