api_endpoint: "http://10.254.138.189:8107"
model: "qwen/qwen-2.5-72b-instruct"
output_dir: "/home/admin/NLP/reward_model/resources/results"
cache_dir: 
splits:
  - gsm8k
  - math
  - olympiadbench
  - omnimath
verifier_type: logicflow
verifier_kwargs:
  constructor_type: targeted
  prefix: predecessors
  suffix: null
  prefix_size: -1
  suffix_size: -1
construction_kwargs:
  max_window_size: 10 
generation_kwargs:
  temperature: 0.0
  max_tokens: 4096
dataset_path: "/home/admin/NLP/reward_model/resources/datasets/ProcessBench-333-graph/targeted"
sample_size: -1
use_voting: false
voting_n: 8
num_workers: 16